language: php

sudo: false

matrix:
    include:
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: hhvm
    allow_failures:
        - php: hhvm
    fast_finish: true

before_install:
    - composer self-update

install:
    - composer --prefer-source install

script:
    - vendor/phpunit/phpunit/phpunit
